# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94301969627c5a854a5c0b127b164d00140f558f15ad3a8d7a5a2f0ee0ba8a095a229d00d5aed43b1cb6a9a474c91f788dc349ac6a61ad17fdd1b65039d362a1

test:
  secret_key_base: d26401c1b3c756e1926cabef80754ac94129c82b6d5baf0ba80dec70b30b93a44320980a9cdca7aa29a3ef6775d4d39a26d84188f2701189c4b46307bd36b7a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
