# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5765af36be21bb791742ca079a11b3aa303b88bc7e1cd20f341b0437c5cbb203b349f13715948e8f6de2c6217c338e23737dbd232c77eaffd4bfdf1866183dbd

test:
  secret_key_base: 222b0bdcf3c62436acb8274bd7c7f95ea7b06fba52227b5be7205fba1745841cf7a093e560bffa50b86e1006dbdabc6eaa82d85f8e2fbe1cba7875294d6c0dec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
